force-app/main/default/objects/Integration_Config__mdt/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <label>Host</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Integration_Config__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONNECT</fullName>
                <default>true</default>
                <label>CONNECT</label>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Config__mdt/fields/Named_Credentials__c.field-meta.xml
<CustomField>
    <fullName>Named_Credentials__c</fullName>
    <label>Named Credentials</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationConfig.cls
public class IntegrationConfig {

    public String host;
    public String method;
    public String namedCredentials;
    public String path;
    public Integer timeout;

    public static IntegrationConfig forName(String devName) {
        Integration_Config__mdt config = fetchIntegrationConfigs(devName);
        
        return new IntegrationConfig(config);
    }

    public IntegrationConfig(Integration_Config__mdt config){
        this.host = config.Host__c;
        this.method = config.Method__c;
        this.namedCredentials = config.Named_Credentials__c;
        this.path = config.Path__c;
        this.timeout = config.Timeout__c?.intValue();
    }
    
    private static Integration_Config__mdt fetchIntegrationConfigs(String devName) {
        return [SELECT Host__c, Method__c, Named_Credentials__c, Path__c, Timeout__c
                  FROM Integration_Config__mdt
                 WHERE DeveloperName = :devName][0];
    }
}